[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI", "Agent", "Deepseek", "Model", "Provider"]
license = ["Apache-2.0"]
name = "ai.model.provider.deepseek"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.model.provider.deepseek"
version = "@toml.version@"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.model.provider.deepseek-native"
version = "@toml.version@"
path = "../native/build/libs/ai.model.provider.deepseek-native-@project.version@.jar"
